Blog app - Views
Ghiftee/blogapp pull request #5
Opened 2021-11-03 18:45 UTC by Ghiftee

I implemented the design from the [wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md) in this milestone.

2021-11-04 22:22 UTC, sinansevgi requested changes
# Changes Required :recycle: 
------

Hi @Ghiftee , 

Good job so far!
Styling looks similar :+1: 
There are some issues that you still need to work on to go further but you are almost there!


 ## Required Changes ♻️
_Please check the inline comments for my suggestions_ :arrow_down:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi

------

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-04 22:22 UTC, sinansevgi commented on app/views/users/index.html.erb
> +<% end %>
[Optional]
- [ ] You can create a partial for users and use this partial. This will make your code cleaner and more abstract.

2021-11-04 22:22 UTC, sinansevgi commented on app/views/posts/index.html.erb
> +    <h4><%= @user.name %>: Comment 5</h4>
- [x] You should render users comments instead of rendering hardcoded HTML elements.

For example
```ruby
 <% post.recent_comments.each do |comment| %>
  <p><%= comment.author.name %>: <%= comment.text %></p> 
 <% end %>
```

2021-11-04 22:22 UTC, sinansevgi commented on app/views/posts/show.html.erb
> +  <h4><%= @user.name %>: Comment 10</h4>
- [x] You should render users comments instead of rendering hardcoded HTML elements.

2021-11-05 00:08 UTC, Ghiftee commented on app/views/posts/index.html.erb
> +    <h4><%= @user.name %>: Comment 5</h4>
Thank you for the suggestion on how to fix it. It was very helpful

2021-11-05 00:08 UTC, Ghiftee commented on app/views/posts/show.html.erb
> +  <h4><%= @user.name %>: Comment 10</h4>
Done

2021-11-05 00:10 UTC, Ghiftee commented on app/views/posts/show.html.erb
> +  <h4><%= @user.name %>: Comment 10</h4>
I have implemented all the required changes

2021-11-05 03:36 UTC, oxenprogrammer approved these changes
Hi @Ghiftee, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-05 07:29 UTC, merged